jasypt:
  encryptor:
    ## 16位
    password: k0fek3wnux55pf6z
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xqmgr
    password: xqmgr
    url: jdbc:mysql://39.99.137.69:3306/xqmgr-dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
#    username: ENC(a44625760f8fc68e8d3c6e3f18f898cd)
#    password: ENC(a44625760f8fc68e8d3c6e3f18f898cd)
#    url: ENC(a44625760f8fc68e8d3c6e3f18f898cd)
