spring:
  profiles:
    active: dev
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

jasypt:
  encryptor:
    bean: sm4StringEncryptor
server:
  port: 9012
  servlet:
    context-path: /xqmgr

logging:
  level:
    com.github.rainsoil.fastapi: debug

# mybatis-plus 配置
mybatis-plus:
  tenant-enable: ture
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  global-config:
    banner: false
    db-config:
      db-type: mysql
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      where-strategy: not_empty
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    jdbc-type-for-null: null

wx:
  miniapp:
    appid: wxfeec83d8721e879f
    secret: 2bf5ee2900f4e405007d1ccacee37ef9